### PR TITLE
Universal File Converter: Csv to Json

### PR DESCRIPTION
**Pull request by scove**
Hello,

I am somewhat new to open source projects. Please let me know if I can improve on anything in this pull request :smile:

### CODE REVIEW

**Comment by scove** [comment]
#55

**Review by bhargavnova — APPROVED** [review]
Looks good :)

**Comment by bhargavnova** [comment]
Hi @scove,
You did a great, even though you are new to open source.
Keep it going.
"Every master was once a beginner"

Thanks for your contribution :)
You can look for more open issues or you can also submit your own code, if interested.

Happy Coding!

**Comment by scove** [comment]
Thank you, you are too kind. Best of luck

**Pull request merged**
