### PR TITLE
making of an image format converting python module

### PR DESCRIPTION
**Pull request by stktyagi**
A python based image format converting module called
(image_converter) that converts user image inputs to different popular formats.

### CODE REVIEW

**Review by bhargavnova — APPROVED** [review]
Looks Good!!

But always remember you should include `if __name__ == "__main__:" so that script can be run as standalone and module,

**Comment by stktyagi** [comment]
I'll make sure, Thank you!

**Comment by stktyagi** [comment]
Hello, @bhargavnova. My merge contribution was excluded from hacktoberfest.
Is there any issue regarding this? Kindly let me know.

**Comment by bhargavnova** [comment]
Does it say anything in particular,
what's the issue?
because when I accept and merge pull requests that should appear on your
hacktoberfest profile.

**Comment by stktyagi** [comment]
It's fixed. Thanks a lot!

**Pull request merged**
