### PR TITLE
Added python script for json to csv

### PR DESCRIPTION
**Pull request by akadeepesh**
solved #33 with folder structure and readme.md file

### CODE REVIEW

**Comment by bhargavnova** [comment]
Hey!
Did you write this script on your own?

**Comment by akadeepesh** [comment]
I wrote the python script and generated readme file accordingly using AI

**Comment by bhargavnova** [comment]
Hi,
but I have doubts because, in the readme file, there is still mention of
[your-name],

It looks like professional code,
I can't accept this, no need to write code from AI, if you want you can
write code on your own, in this issue.

**Comment by akadeepesh** [comment]
Bro, trust me i just pasted the code on Gpt and asked for readme.md, I am working for automation using python from a long time, I can fix the readme [your-name] issue. But code is that only, np it's ok if you won't accept

**Comment by bhargavnova** [comment]
So you have tested this code on a certain JSON file right?

**Comment by akadeepesh** [comment]
yes i did, 
image

**Comment by bhargavnova** [comment]
Okay, the code seems to be working, but still have an issue
mapping = {'Name': 'full_name', 'Email': 'contact.email', 'Phone': 'contact.phone'}
don't you think that key should be in the CSV header, and the value is pointing out the JSON data-position?

I still have doubts regarding this, if I accept this, it won't be fair to other developers and participants.
So I will have to close this request, I am not marking it as `spam`, so it won't affect you.

Hope you get it.
Thank you.

**Pull request closed without merging**
