### PR TITLE
Created random_sleep_time_module

### PR DESCRIPTION
**Pull request by avyuktsoni0731**
Closes issue #4 

Made a Python module named "random_sleep_time_module"

1. Imported time module.
2. Imported random module.
3. Made a definition named "random_time_sleep()".
4. Made user enter the startTime (left hand limit for choosing random time) & endTime (right hand limit for choosing random time).
5. Made user enter the number of seconds from which they want to begin the countdown.
6. Made a while loop for the condition, till when the countdown hits 0.
7. Inside the while loop, made conversions of time inputted in seconds to convert it in "hours:minutes:seconds" format.
8. Made nested if-elif-else loops for different conditions of countdown time.
9. Have put comments on every step being performed.

Please run the main.py file by putting different values to verify the program.

Let me know if any changes are required. 

Thanks a lot ^_^

### CODE REVIEW

**Review by bhargavnova — CHANGES_REQUESTED** [review]
Hi @avyuktsoni0731,
I appreciate your effort in this code,
I checked the code, but it requires changes, I think you still didn't understand the objective here.

So basically we want the script to stop execution whenever we need to use this module.
1. No need to ask for user input, the user can directly pass `min_seconds`, and `max_seconds` in the function itself.
2. then user `random_number = random.randint()` to get a random number from these two values.
3. then user for loop or while loop, to go over all `range(1, random_number+1)`.
4. because we need to update the live count on the console, that's why we need loops, otherwise it was just `time.sleep(random_number)`
5. Now Use the `sys module` which is built in for console interaction, check the documentation you will find it's usage. (tip:: \r is what we are looking for.)
6. So you can try to do this again, one more tip this code won't go more the 10 lines,
7. So hope you understand now.

If you think you can't do it, no worries, I can remove the assignment, and you can submit whatever you think can be helpful, on this repo.

Once again, thanks for your efforts. : )
Happy Coding!!

**Comment by bhargavnova** [comment]
As you can see here,
we got `min_time = 20`, `max_time = 21`
using random found `random_number = 21`

as you can see countdown is changing at the same line, because of `sys` using `\r, which brings cursor to beginning or the line, where print() always adds \n at the end, if you don't mention end=" "`
`so this was second tip, you can also use print("" , end="\r")`

sleeping for 21 seconds reached 17
sleeping for 21 seconds reached 17

sleeping for 21 seconds reached 16
sleeping for 21 seconds reached 16

sleeping for 21 seconds reached 14
sleeping for 21 seconds reached 14

**Comment by avyuktsoni0731** [comment]
Hi @bhargavnova ! Thank you for explaining with such patience, really appreciate that. I am new to open source contributions, and wanted to contribute in a good python project. Took me a while to understand the assignment, but i suppose now I get it. Made it as close as possible, and as concise as possible. 

Please have a look at it. 

Thanks a lot :)

**Review by bhargavnova — APPROVED** [review]
Hey @avyuktsoni0731 ,
Now you got the point, your code looks good, just need some changes that I have done.

every time this function calls `we don't need to take arguments from the user, that will stop the script from running, so that should be passed into the function`.

also `time.sleep(randomTime)` #that's not right,
it will be `time.sleep(1)`

because we are going through a loop, and it should be a 1-second gap, otherwise every time function will sleep more then expected.

I appreciate your efforts, so just note this, you are still in the learning phase, and you will develop logic at your own pace.

Also, you can check other issues or submit your own code which you think can be useful.

Thanks : )
Happy Coding!!

**Pull request merged**
